version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: production
    depends_on:
      - db
      - redis
    networks:
      - laravel

  web:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - laravel

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-worker
    command: supervisord -c /etc/supervisord.conf
    volumes:
      - .:/var/www/html
    depends_on:
      - redis
      - db
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
